version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - people_data:/app/data
    restart: unless-stopped  # Автоматический перезапуск при ошибке
    environment:
      - PYTHONUNBUFFERED=1  # Немедленный вывод логов

volumes:
  people_data: 